language: node_js
cache: yarn

node_js:
  - '7'
before_install:
  - yarn

script:
  - yarn test
  - yarn lint

after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
