version: 2
jobs:
   build:
     working_directory: ~/redux-pouchdb-sync-models
     docker:
       - image: circleci/node:6
     steps:
       - checkout
       - run: yarn
       - run: yarn test
       - run: yarn lint
       - deploy:
          name: Release master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run semantic-release || exit 0
            fi
