export type LOAD_MODELS = '@@sync/LOAD_MODELS';
export const LOAD_MODELS: LOAD_MODELS = '@@sync/LOAD_MODELS';
export type INSERT_MODEL = '@@sync/INSERT_MODEL';
export const INSERT_MODEL: INSERT_MODEL = '@@sync/INSERT_MODEL';
export type INSERT_BULK_MODELS = '@@sync/INSERT_BULK_MODELS';
export const INSERT_BULK_MODELS: INSERT_BULK_MODELS =
  '@@sync/INSERT_BULK_MODELS';
export type UPDATE_MODEL = '@@sync/UPDATE_MODEL';
export const UPDATE_BULK_MODELS: UPDATE_BULK_MODELS =
  '@@sync/UPDATE_BULK_MODELS';
export type UPDATE_BULK_MODELS = '@@sync/UPDATE_BULK_MODELS';
export const UPDATE_MODEL: UPDATE_MODEL = '@@sync/UPDATE_MODEL';
export type REMOVE_MODEL = '@@sync/REMOVE_MODEL';
export const REMOVE_MODEL: REMOVE_MODEL = '@@sync/REMOVE_MODEL';
export type REMOVE_BULK_MODELS = '@@sync/REMOVE_BULK_MODELS';
export const REMOVE_BULK_MODELS: REMOVE_BULK_MODELS =
  '@@sync/REMOVE_BULK_MODELS';
export type MODEL_ERROR = '@@sync/ERROR';
export const MODEL_ERROR: MODEL_ERROR = '@@sync/ERROR';
export type INITIALIZED = '@@sync/INITIALIZED';
export const INITIALIZED: INITIALIZED = '@@sync/INITIALIZED';
export type MODEL_INITIALIZED = '@@sync/MODEL_INITIALIZED';
export const MODEL_INITIALIZED: MODEL_INITIALIZED = '@@sync/MODEL_INITIALIZED';

export type OPERATION_CHANGES = 'OPERATION_CHANGES';
export const OPERATION_CHANGES: OPERATION_CHANGES = 'OPERATION_CHANGES';
export type OPERATION_FETCH_DOCS = 'OPERATION_FETCH_DOCS';
export const OPERATION_FETCH_DOCS: OPERATION_FETCH_DOCS =
  'OPERATION_FETCH_DOCS';
export type OPERATION_INSERT = 'OPERATION_INSERT';
export const OPERATION_INSERT: OPERATION_INSERT = 'OPERATION_INSERT';
export type OPERATION_BULK_INSERT = 'OPERATION_BULK_INSERT';
export const OPERATION_BULK_INSERT: OPERATION_BULK_INSERT =
  'OPERATION_BULK_INSERT';
export type OPERATION_UPDATE = 'OPERATION_UPDATE';
export const OPERATION_UPDATE: OPERATION_UPDATE = 'OPERATION_UPDATE';
export type OPERATION_BULK_UPDATE = 'OPERATION_BULK_UPDATE';
export const OPERATION_BULK_UPDATE: OPERATION_BULK_UPDATE =
  'OPERATION_BULK_UPDATE';
export type OPERATION_REMOVE = 'OPERATION_REMOVE';
export const OPERATION_REMOVE: OPERATION_REMOVE = 'OPERATION_REMOVE';
export type OPERATION_BULK_REMOVE = 'OPERATION_BULK_REMOVE';
export const OPERATION_BULK_REMOVE: OPERATION_BULK_REMOVE =
  'OPERATION_BULK_REMOVE';
